### ISSUE TITLE
Some small enhancements (dockerfile & option for report output path )

### ISSUE THREAD

**Issue by ps-xaf** [adliance/Togglr#7]
Hi folks,

thank you for this nice little tool for creating reports from toggl.

Not being a c# developer I added a dockerfile to make changes easier using the sdk/runtime and to adopt the tool easier on other OSs.

Also I added an option for the report destination as it seems to place it in the current pwd where the binary gets executed.

To summarize:
* docker makes building and running your tool easier
* report output path provides some flexibility (e.g. running report generation regular in a ci/cd pipeline)

**Comment by saxx** [comment]
Thank you very much for the ticket and the associated PR - very happy to merge it, thank you for your contribution!
